/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AgentReports: () => import('#controllers/agent_reports_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  ServerAgent: () => import('#controllers/server_agent_controller'),
  Servers: () => import('#controllers/servers_controller'),
  Session: () => import('#controllers/session_controller'),
}
