/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  DaemonReports: () => import('#controllers/daemon_reports_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  ServerDaemon: () => import('#controllers/server_daemon_controller'),
  Servers: () => import('#controllers/servers_controller'),
  Session: () => import('#controllers/session_controller'),
}
