/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ServerReportSchema extends BaseModel {
  static $columns = [
    'bootId',
    'capturedAt',
    'cpuPct',
    'cpuTempC',
    'createdAt',
    'diskBusyPct',
    'diskReadBps',
    'diskUsedPct',
    'diskWriteBps',
    'id',
    'load1',
    'load15',
    'load5',
    'memUsedPct',
    'netRxBps',
    'netTxBps',
    'payload',
    'processCount',
    'reportSeq',
    'serverId',
    'swapUsedPct',
    'uptimeSeconds',
  ] as const
  $columns = ServerReportSchema.$columns
  @column()
  declare bootId: string
  @column.dateTime()
  declare capturedAt: DateTime
  @column()
  declare cpuPct: number | null
  @column()
  declare cpuTempC: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare diskBusyPct: number | null
  @column()
  declare diskReadBps: number | null
  @column()
  declare diskUsedPct: number | null
  @column()
  declare diskWriteBps: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare load1: number | null
  @column()
  declare load15: number | null
  @column()
  declare load5: number | null
  @column()
  declare memUsedPct: number | null
  @column()
  declare netRxBps: number | null
  @column()
  declare netTxBps: number | null
  @column()
  declare payload: string
  @column()
  declare processCount: number | null
  @column()
  declare reportSeq: number
  @column()
  declare serverId: number
  @column()
  declare swapUsedPct: number | null
  @column()
  declare uptimeSeconds: number | null
}

export class ServerSchema extends BaseModel {
  static $columns = [
    'address',
    'createdAt',
    'daemonBootId',
    'daemonKey',
    'daemonLastReportAt',
    'daemonListenUrl',
    'daemonVersion',
    'id',
    'location',
    'name',
    'severity',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = ServerSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare daemonBootId: string | null
  @column()
  declare daemonKey: string | null
  @column.dateTime()
  declare daemonLastReportAt: DateTime | null
  @column()
  declare daemonListenUrl: string | null
  @column()
  declare daemonVersion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string
  @column()
  declare name: string
  @column()
  declare severity: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
